[project]
name = "redfox"
version = "0.2.0"
description = "The server for serving agent runs when prompted"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "e2b>=2.46.4",
    "fastapi[standard]>=0.139.0",
    "google-genai>=2.20.0",
    "groq>=1.5.0",
    "logfire>=5.0.0",
    "motor>=3.7.1",
    "openai>=2.44.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.51",
    "strands-agents>=1.55.0",
    "strands-agents-tools>=0.8.8",
    "uvicorn>=0.50.0",
]
